### ISSUE TITLE
markdownlint issues

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/www.ianlewis.org#17]
- [x] MD009/no-trailing-spaces (#25)
- [x] MD010/no-hard-tabs (#26)
- [x] MD014/commands-show-output (#34)
- [x] MD018/no-missing-space-atx (#100)
- [x] MD025/single-title/single-h1 (#124)
- [x] MD026/no-trailing-punctuation (#100)
- [x] MD029/ol-prefix (#100)
- [x] MD030/list-marker-space (#100)
- [x] MD036/no-emphasis-as-heading/no-emphasis-as-header (#100)
- [x] MD037/no-space-in-emphasis (#100)
- [x] MD038/no-space-in-code (#100)
- [x] MD039/no-space-in-links (#100)
- [x] MD040/fenced-code-language (#100)
- [x] MD046/code-block-style (#100)
- [x] MD025/single-title/single-h (#165)

**Comment by ianlewis** [comment]
Broke out the alt-text issue to its own issue (#339). So this can be closed.
